### ISSUE TITLE
Inspector-less Node.js build

### ISSUE THREAD

**Issue by TimothyGu** [devsnek/node-repl-prototype#2]
Should we make it clear that this is not designed to work on Node.js builds with inspector disabled? Or should we try to make it work? (I fear that a REPL that doesn't work with some Node.js configurations may be difficult to be accepted to core.)

**Comment by devsnek** [comment]
we could factor out our inspector usage and stub it with other things when inspector isn't available.

e.g. Runtime.evaluate calls vm and Runtime.getProperties is just a function that throws or something.
